# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b0af99175ecde36674a912b8bcfb5d0ef2c631cd3c9d0b9b981c99f721e63abf8bbe29e79980b8ee955352690c02009913b55d633013c3b434ad962ef8a5efa

test:
  secret_key_base: 4b43d271d726427a15a9a9e88dbc7ab1f1408035261937ad7f37785a8e1e336e2c7a086468164f3491011e78b65f106c8955c04e2cc7548a82a00a6548888f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
